{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f9200244",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name: nithin\n",
      "Phone Number: 6305585433\n",
      "Name: chethan\n",
      "Phone Number: 6301286034\n",
      "Name: akhil\n",
      "Phone Number: 1255451596\n",
      "Name: ravi\n",
      "Phone Number: 1259786542\n",
      "Name: ram\n",
      "Phone Number: 9876523148\n",
      "Name: ahiv\n",
      "Phone Number: 9876556542\n",
      "Name: abhi\n",
      "Phone Number: 9754363658\n",
      "Name: tinku\n",
      "Phone Number: 458987855565\n",
      "Name: rythh\n",
      "Phone Number: 9876668546\n",
      "Name: lilly\n",
      "Phone Number: 589987445\n",
      "\n",
      "Name\t\t\tPhone Number\n",
      "\n",
      "nithin\t\t\t6305585433\n",
      "chethan\t\t\t6301286034\n",
      "akhil\t\t\t1255451596\n",
      "ravi\t\t\t1259786542\n",
      "ram\t\t\t9876523148\n",
      "ahiv\t\t\t9876556542\n",
      "abhi\t\t\t9754363658\n",
      "tinku\t\t\t458987855565\n",
      "rythh\t\t\t9876668546\n",
      "lilly\t\t\t589987445\n",
      "nEnter Search Term: nithin\n",
      "Search Result\n",
      "Name:nithin, Phone Number: 6305585433\n"
     ]
    }
   ],
   "source": [
    "### How to add new mobile numbers in the contact book?\n",
    "\n",
    "\n",
    "## Calling the values of the  Phone numbers and the names.\n",
    "\n",
    "\n",
    "names = []\n",
    "\n",
    "phone_numbers = []\n",
    "\n",
    "\n",
    "#Number of Phone numbers to be added in the list.\n",
    "\n",
    "\n",
    "num = 10\n",
    "\n",
    "\n",
    "\n",
    "# Taking the input from the user by using the for loop.\n",
    "\n",
    "\n",
    "for i in range(num):\n",
    "    \n",
    "## Taking the name from the user.\n",
    "\n",
    "    \n",
    "    name = input(\"Name: \")\n",
    "    \n",
    "## Taking the phone number from user.\n",
    "    \n",
    "    phone_number = input(\"Phone Number: \")\n",
    "    \n",
    "## then adding the names to the list.\n",
    "    \n",
    "    names.append(name)\n",
    "\n",
    "## and addimg the numbers to the list.     \n",
    "    \n",
    "    phone_numbers.append(phone_number)\n",
    "    \n",
    "    \n",
    "    \n",
    "print(\"\\nName\\t\\t\\tPhone Number\\n\")\n",
    "\n",
    "\n",
    "\n",
    "for i in range(num):\n",
    "    \n",
    "    \n",
    "    print(\"{}\\t\\t\\t{}\".format(names[i], phone_numbers[i]))\n",
    "    \n",
    "    \n",
    "    \n",
    "search_term = input(\"nEnter Search Term: \")\n",
    "\n",
    "\n",
    "print(\"Search Result\")\n",
    "\n",
    "\n",
    "if search_term in names:\n",
    "    \n",
    "    \n",
    "    index = names.index(search_term)\n",
    "    \n",
    "    \n",
    "    \n",
    "    phone_number = phone_numbers[index]\n",
    "    \n",
    "    ## then searching the name and number in the list.\n",
    "    \n",
    "    \n",
    "    print(\"Name:{}, Phone Number: {}\".format(search_term,phone_number))\n",
    "    \n",
    "   ## If the name is not found in the list.\n",
    "\n",
    "else:\n",
    "    \n",
    "    \n",
    "    print(\"Name not found\")\n",
    "    \n",
    "    \n",
    "    \n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "17e0437b",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e0083819",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
